/***************************************************************************\
||             
||  $Header: /root/MAILSTREAMLIBRARY/ArchiveTables.h,v 1.1.4.1 2005/12/07 14:46:42 markm Exp $
||
||  Copyright © 2002 Deerfield.com, all rights reserved
||                                         
||  COMMENTS:   Archive Table Functions
||              
\\*************************************************************************/

// only include once
#pragma once


// TODO: Handle contant IDs like Unassigned Ticketbox, Administrators Group, 
// and Administrator agent

// TODO: Fix ArchiveTableIDs enumeration so that tables can be added
// without changing existing IDs.

// Definition of Table IDs
// Note that these are defined in order in which they can be created
// in a fresh database to avoid foreign key constraint problems.
enum ArchiveTableIDs
{
	TABLEID_StyleSheets,
	TABLEID_ObjectTypes,
	TABLEID_LogEntryTypes,
	TABLEID_LogSeverity,
	TABLEID_PersonalDataTypes,
	TABLEID_AlertEvents,
	TABLEID_AlertMethods,
	TABLEID_ServerParameters,
	TABLEID_VirusScanStates,
	TABLEID_Registry,						
	TABLEID_TicketStates,
	TABLEID_Priorities,
	TABLEID_OutboundMessageStates,
	TABLEID_OutboundMessageTypes,
	TABLEID_MessageSourceTypes,
	TABLEID_StdResponseCategories,
	TABLEID_TicketBoxViewTypes,	
	TABLEID_Objects,
	TABLEID_Agents,
	TABLEID_Groups,	
	TABLEID_Signatures,
	TABLEID_Contacts,
	TABLEID_PersonalData,
	TABLEID_StandardResponses,
	TABLEID_TicketBoxFooters,
	TABLEID_TicketBoxHeaders,
	TABLEID_TicketBoxes,
	TABLEID_Tickets,
	TABLEID_MessageDestinations,
	TABLEID_MessageSources,
	TABLEID_RoutingRules,
	TABLEID_OutboundMessages,
	TABLEID_InboundMessages,	
	TABLEID_ContactNotes,
	TABLEID_AccessControl,
	TABLEID_AgentGroupings,
	TABLEID_AlertMsgs,
	TABLEID_Alerts,
	TABLEID_ForwardCCAddresses,
	TABLEID_ForwardToAddresses,
	TABLEID_MatchFromAddresses,
	TABLEID_MatchText,
	TABLEID_MatchToAddresses,
	TABLEID_IPRanges,
	TABLEID_InboundMessageAttachments,
	TABLEID_InboundMessageQueue,
	TABLEID_OutboundMessageAttachments,
	TABLEID_OutboundMessageContacts,
	TABLEID_OutboundMessageQueue,
	TABLEID_StandardResponseUsage,
	TABLEID_StdResponseAttachments,
	TABLEID_StdResponseFavorites,
	TABLEID_TicketBoxViews,
	TABLEID_TicketContacts,
	TABLEID_TicketNotes,
	TABLEID_UIDLData,
	TABLEID_CustomDictionary,
	TABLEID_TicketActions,
	TABLEID_TicketHistory,
	TABLEID_Attachments,
	TABLEID_InboundMessageRead,
	TABLEID_SRKeywordResults,
	TABLEID_TicketNotesRead,
	TABLEID_Folders,	
	TABLEID_AgeAlerts,
	TABLEID_AgeAlertsSent,
	TABLEID_AutoMessages,
	TABLEID_AutoMessagesSent,
	TABLEID_AutoResponses,
	TABLEID_AutoResponsesSent,
	TABLEID_TicketBoxOwners,
	TABLEID_TicketBoxTicketBoxOwner,
	TABLEID_TicketBoxRouting,
	TABLEID_TicketCategories,
	TABLEID_WaterMarkAlerts,	
	TABLEID_ProcessingRules,
	TABLEID_MatchTextP,
	TABLEID_MatchFromAddressP,
	TABLEID_MatchToAddressP,
    TABLEID_ReportCustom,
	TABLEID_ReportObjects,
	TABLEID_ReportTypes,
	TABLEID_ReportStandard,
	TABLEID_ReportScheduled,
	TABLEID_ReportResultRows,
	TABLEID_ReportResults,	
	TABLEID_TicketFields,
	TABLEID_TicketFieldsTicket,
	TABLEID_TicketFieldsTicketBox,
	TABLEID_AgentActivities,
	TABLEID_AgentActivityLog,
	TABLEID_AgentTicketCategories,
	TABLEID_TicketFieldViews,
	TABLEID_VoipDialingCodes,
	TABLEID_VoipExtensions,
	TABLEID_VoipServers,
	TABLEID_VoipServerTypes,
	TABLEID_ApprovalObjectTypes,
	TABLEID_Approvals,
	TABLEID_Log,
	TABLEID_Servers,
	TABLEID_ServerTaskTypes,
	TABLEID_ServerTasks,
	TABLEID_NoteAttachments,
	TABLEID_AutoActionTypes,
	TABLEID_AutoActionEvents,
	TABLEID_AutoActions,
	TABLEID_OfficeHours,
	TABLEID_AgentContacts,
	TABLEID_AgentRouting,
	TABLEID_TicketLinks,
	TABLEID_TicketLinksTicket,
	TABLEID_ContactGroups,
	TABLEID_ContactGrouping,
	TABLEID_TicketFieldTypes,
	TABLEID_TicketFieldOptions,
	TABLEID_MessageTracking,
	TABLEID_Bypass,
	TABLEID_Email,
	TABLEID_TimeZones,
	TABLEID_Dictionary,
	TABLEID_OAuthHosts,
	TABLEID_Archives,
	TABLEID_COUNT
};
