////////////////////////////////////////////////////////////////////////////////
//
//	$Header: /root/MAILSTREAMENGINE/EngineErrorCodes.h,v 1.1.4.2 2006/01/17 14:23:56 markm Exp $
//
//  Copyright © 2002 Deerfield.com, all rights reserved
//
////////////////////////////////////////////////////////////////////////////////

#ifndef ENGINE_ERROR_CODES_H
#define ENGINE_ERROR_CODES_H


#define EMS_STRING_RTR_ROUTE_TO_TRASH		L"Routing message to trash"
#define EMS_STRING_RTR_DELETE_PERMANENTLY	L"Deleting message permanently"
#define EMS_STRING_ERROR_FINDING_MAILCOMPONENTS_EXPORT L"Could not find MailComponents export: %s"
#define EMS_STRING_ERROR_MAILCOMPONENTS_INIT L"InitMailComponents failed with Error %d"
#define EMS_STRING_ERROR_MAILCOMPONENTS_SHUTDOWN L"ShutdownMailComponents failed with Error %d"
#define EMS_STRING_ERROR_MAILCOMPONENTS_CHECKMAILNOW L"CheckMailNow failed with Error %d"
#define EMS_STRING_ERROR_MAILCOMPONENTS_SENDMAILNOW L"SendMailnow failed with Error %d"
#define EMS_STRING_ERROR_MAILCOMPONENTS_TESTPOP3AUTH L"TestMessageSourceAuth failed with Error %d"
#define EMS_STRING_ERROR_MAILCOMPONENTS_TESTSMPTAUTH L"TestSMTPAuth failed with Error %d"
#define EMS_STRING_ERROR_MAILCOMPONENTS_REFRESHSRVPRM L"RefreshServerParams failed with Error %d"

typedef enum EngineErrorCodes 
{

	// Informational messages
	E_EngineStarting			=	EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,1),	
	E_EngineStopping			=	EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,2),
	E_GotMessage				=	EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,3),	
	E_CreatedContact			=   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,4),
	E_RuleMatch					=   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,5),
	E_PutInTicketBox			=   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,6),
	E_RouteToTrash				=	EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,7),
	E_DeletePermanently			=   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,8),
	E_RoutingException			=	EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_ROUTING_RULES,9),	
	E_ErrorLoadingMsgComponents	=	EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_MESSAGE_PROCESSING,10),	
	E_ErrorCallingMsgComponents	=	EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_MESSAGE_PROCESSING,11),	
	E_DBMaintenanceInfo			=   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_DATABASE_MAINTENANCE,12),
	E_DBMaintErrorUnhandled		=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_DATABASE_MAINTENANCE,13),
	E_DBMaintErrorWritingToFile	=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_DATABASE_MAINTENANCE,14),
	E_DBMaintErrorODBC			=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_DATABASE_MAINTENANCE,15),
	E_DBMaintErrorArchive		=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_DATABASE_MAINTENANCE,16),
	E_DBMaintErrorRestore		=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_DATABASE_MAINTENANCE,17),
	E_DBMaintErrorImport		=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_DATABASE_MAINTENANCE,18),
	E_RegistrationWarning		=   EMSERROR(EMS_LOG_SEVERITY_WARNING,EMSERR_ROUTING_ENGINE,EMS_LOG_PRODUCT_REGISTRATION,19),
	E_VirusScanningInfo			=   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_VIRUS_SCANNING,20),
	E_VirusScanningError		=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_VIRUS_SCANNING,21),
	E_DBMaintErrorBackup		=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_DATABASE_MAINTENANCE,22),
	E_TicklerError		        =   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_TICKLER_SYSTEM,23),
	E_TicklerStarting           =   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_TICKLER_SYSTEM,24),
	E_TicklerInfo               =   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_TICKLER_SYSTEM,25),
	E_Reporter					=   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_REPORTER_SYSTEM,26),
	E_DBMonitorError		    =   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_DBMONITOR,27),
	E_DBMonitorStarting         =   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_DBMONITOR,28),
	E_DBMonitorInfo             =   EMSERROR(EMS_LOG_SEVERITY_INFORMATIONAL,EMSERR_ROUTING_ENGINE,EMS_LOG_DBMONITOR,29),
	E_WorkerODBCError		    =   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_WORKER_THREAD,30),
	E_WebSessionError		    =   EMSERROR(EMS_LOG_SEVERITY_ERROR,EMSERR_ROUTING_ENGINE,EMS_LOG_WEBSESSION_THREAD,31)	

} EngineErrorCodes;

#endif